export const SKILLS = [
  {
    slug: 'communication',
    name: 'Communication',
    icon: '💬',
    bg: '#FAF5FC',
    color: '#9C51B6',
    text: '#612E75',
    desc: 'Speaking, listening, expressing ideas clearly',
  },
  {
    slug: 'leadership',
    name: 'Leadership',
    icon: '🦁',
    bg: '#FFFBEB',
    color: '#D97706',
    text: '#92400E',
    desc: 'Initiative, decisions, responsibility',
  },
  {
    slug: 'critical-thinking',
    name: 'Critical Thinking',
    icon: '🧠',
    bg: '#EFF6FF',
    color: '#2563EB',
    text: '#1E40AF',
    desc: 'Problem-solving, reasoning, questioning',
  },
  {
    slug: 'creativity',
    name: 'Creativity',
    icon: '🎨',
    bg: '#FDF2F8',
    color: '#DB2777',
    text: '#9D174D',
    desc: 'Imagination, original ideas, expression',
  },
  {
    slug: 'resilience',
    name: 'Resilience',
    icon: '💪',
    bg: '#F0FDF4',
    color: '#16A34A',
    text: '#14532D',
    desc: 'Handling setbacks, persistence, growth',
  },
  {
    slug: 'social-skills',
    name: 'Social Skills',
    icon: '🤝',
    bg: '#FFF7ED',
    color: '#EA580C',
    text: '#9A3412',
    desc: 'Empathy, teamwork, relationships',
  },
  {
    slug: 'emotional-intelligence',
    name: 'Emotional Intelligence',
    icon: '❤️',
    bg: '#ECFEFF',
    color: '#0891B2',
    text: '#155E75',
    desc: 'Self-awareness, emotions, understanding others',
  },
] as const

export type SkillSlug = (typeof SKILLS)[number]['slug']
